api/handlers/event.js
Improved our findEvents handler to return most relevant events for a particular user in addition to the events that the user is part of already (i.e. he created, was invited to, is going to)
=> Improved GET /events/find call with Complex Logic

api/test/validator.js
```
18:07 $ npm run test
> mapp@1.0.0 test /Users/Adriano/go/src/github.com/adrianosela/mapp/api
> mocha
Test Validate New User
Positive: Successful Validation
✓ should return ok = true with valid parameters
Negative: No Email
✓ should return an error when no email is provided
Negative: No Password
✓ should return an error when no password is provided
Negative: No Name
✓ should return an error when no name is provided
Negative: Invalid Email
✓ should return an error when the provided email is not valid
5 passing (8ms)
```
=> New User Validator tests

api/README.md, api/handlers/auth.js, api/handlers/event.js, api/handlers/push.js, api/handlers/user.js, api/index.js, api/notifications/notifications.js, api/package-lock.json, api/package.json, api/store/datastore.js
Decided to utilize a logger instead of console.trace statements. Also, cleaned up README
=> Added Logger

api/README.md, app/README.md
Still trying to fix the codacy issues with our README.md files
=> Fixing README.md files

api/README.md
Hopefully last README change ...
=> Added language to readme file

api/test/validator.js, api/validator/validator.js
```
npm run test
> mapp@1.0.0 test /Users/Adriano/go/src/github.com/adrianosela/mapp/api
> mocha
Test Validate Existing User
Positive: Successful Validation
✓ should return ok = true with valid parameters
Negative: No Email
✓ should return an error when no email is provided
Negative: No Password
✓ should return an error when no password is provided
Negative: Invalid Email
✓ should return an error when the provided email is not valid
Test Validate New User
Positive: Successful Validation
✓ should return ok = true with valid parameters
Negative: No Email
✓ should return an error when no email is provided
Negative: No Password
✓ should return an error when no password is provided
Negative: No Name
✓ should return an error when no name is provided
Negative: Invalid Email
✓ should return an …
```
=> Moar Tests

api/handlers/event.js
Based on other teams code review, improved and optimized our logic for retrieving the best events for users.
=> Improved GetRelevantEvents for User

api/handlers/event.js
Fixed logic error to sort events array by descending order instead of ascending.
=> Fixed Logic Error

api/handlers/user.js, api/package-lock.json
closes https://github.com/adrianosela/mapp/issues/99
=> implement unfollow user

api/handlers/event.js, api/routes/event.js, api/routes/user.js
Delete Event call implemented. User Token and event Id is required. If event creator is the requesting user, then event gets deleted.
=> Implemented Delete Event Call

api/handlers/user.js, api/routes/user.js
closes https://github.com/adrianosela/mapp/issues/96
=> implement unsubscribe from event

api/.eslintrc.json, api/package.json
Tell our linter to leave our tests alone!
=> Turn Jest flag on in .eslintrc

app/lib/components/router.dart, app/lib/controllers/eventController.dart, app/lib/screens/createdEvents.dart, app/lib/screens/eventScreen.dart, app/lib/screens/map.dart, app/lib/screens/savedEvents.dart, app/lib/screens/searchedEvents.dart
event page that opens when an event is tapped from createdEvents, Saved Events, markers on the map, and search events
*Currently on displays the event name, need to add event details and a going/ stop going functionality
=> event page tied in

api/handlers/user.js
Modified searchUsers Handler to return simplified Users Object (including id and name) instead of just id.
=> Updated searchUsers Handler

app/lib/controllers/eventController.dart, app/lib/models/eventModel.dart, app/lib/screens/eventScreen.dart, app/lib/screens/map.dart, app/pubspec.yaml
Logic added to event page:
Display event info
Directions button that opens directions in google maps
going button to subscribe to an event
For this to work you will need to completely uninstall the app and reinstall
*Note event page looks like complete shit right now, will be made to look nice in another pr, just focusing on completing app logic for now
=> Events page logic

app/lib/controllers/userController.dart, app/lib/screens/friends.dart
Search for users from the friends side bar and add users as friends
=> user search

.travis.yml
=> Add MongoDB service to travis CI config

api/handlers/auth.js, api/index.js, api/server.js
Cleaned up Auth Handlers based on unit tests
=> Refactor Auth Handlers

api/__tests__/integration/auth.test.js
Added Negative Register Case to Auth Integration Tests
=> Added Test Case to Auth Integration Tests

app/lib/controllers/userController.dart, app/lib/screens/friends.dart
Friend Page fixes,
Remove friends, add searched friends, invite only added friends to events
=> Friends page fixes

api/Makefile, api/__tests__/integration/event.test.js, api/package.json
I HATE THIS
Implemented Integration Tests for 6 out of 7 Endpoints (invite doesn't pass because of notifications)
Also modified some script to have unit and integration tests running separately
=> Implemented Some Integration Tests for Event Endpoints

app/lib/controllers/eventController.dart, app/lib/screens/map.dart
Radius slider that can be used to update the map event search space
=> update radius and map

api/__tests__/integration/user.test.js
Still missing:
- GET /user/pending
- POST /user/declineInvite
- POST /user/unfollow
- POST /user/unsubscribed
=> Added Some User Endpoints Integration Tests

api/__tests__/integration/user.test.js
=> Added Missing User Endpoints Integration Tests

api/__tests__/unit/authHandler.test.js, api/handlers/auth.js, api/package-lock.json, api/package.json
=> auth handler unit tests

api/handlers/event.js
Based on non-functional req., made our GET /event check for private events
=> Implemented Private Get Event

app/lib/components/reusableFunctions.dart, app/lib/screens/createdEvents.dart
View for the announcement creator, I will add in the api call when it is complete on the backend
=> announcment creator view

api/handlers/event.js, api/models/announcement.js, api/package.json, api/routes/event.js, api/utils/event.js
PLEASE EVERYONE REVIEW. Given time constraints, I didn't have much time to test thoroughly so please review very carefully. It should be easy to follow even if you dont know much javascript. @chrisneuf please let me know of any issues once you start testing with front-end. @oleksandran let me know if there is a problem with the notifications.
=> Implemented Event Announcements

api/__tests__/integration/user.test.js, api/handlers/user.js, api/routes/user.js
Updated user search to:
- avoid returning myself
- indicate if a user is my friend or not
- removed case sensitivity
=> Updated User Search

api/handlers/event.js
Added relevance field to categorize events based on relevance to the user
=> Updated Find Events Functionality

api/handlers/event.js
Modified updateEvent handler to deal with eventId separated from the event object.
=> Modified UpdateEvent

api/__tests__/unit/eventHandler.test.js, api/__tests__/unit/userHandler.test.js, api/handlers/event.js, api/handlers/user.js, api/utils/event.js, api/utils/user.js
Added:
- Notify Users when you follow them
- Changed notification message for announcement to not show the actual message (could be very long)
- Added check to avoid a creator to subscribe to his own event
- Some cleanup
=> Notify New Followers + Cleanup

api/index.js, api/reminders/reminders.js, api/utils/event.js
Also fixed typo from previous PR
=> Implemented Reminders

app/lib/controllers/eventController.dart, app/lib/models/announcementModel.dart, app/lib/screens/createdEvents.dart, app/lib/screens/eventScreen.dart
App functionality done putas :)
=> announcments works

app/lib/main.dart
=> phone can't rotate

app/lib/screens/eventScreen.dart, app/lib/screens/map.dart
=> Card event screen

api/index.js, api/package-lock.json, api/package.json
we need a more controlled way of running this thing. Cron allows us to schedule a function to run with a regular expression. https://crontab.guru/every-1-hour
=> better way of scheduling
